name: Render Resume Service

on:
  schedule:
    # 12:00 Asia/Manila = 04:00 UTC, every day
    - cron: "0 4 * * *"
  workflow_dispatch: {}

jobs:
  resume:
    runs-on: ubuntu-latest
    env:
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }} 
    steps:
      - name: Check required secrets
        run: |
          test -n "$RENDER_API_KEY" || { echo "Missing RENDER_API_KEY"; exit 1; }
          test -n "$SERVICE_ID"     || { echo "Missing RENDER_SERVICE_ID"; exit 1; }

      - name: Resume service
        run: |
          echo "Resuming ${SERVICE_ID}"
          curl -fsS -X POST \
            --url "https://api.render.com/v1/services/${SERVICE_ID}/resume" \
            --header "accept: application/json" \
            --header "Authorization: Bearer ${RENDER_API_KEY}"
          echo "OK"
